# Generated by Django 6.0.4 on 2026-04-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('NAO_URGENTE', 'nao_urgente'), ('URGENTE', 'urgente')], default='nao_urgente', max_length=20),
        ),
    ]
