# Generated by Django 6.0.4 on 2026-04-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('nao_urgente', 'Nao urgente'), ('urgente', 'Urgente')], default='nao_urgente', max_length=20),
        ),
    ]
