# Generated by Django 6.0.4 on 2026-04-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_tarefa_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('NAO_URGENTE', 'Nao urgente'), ('URGENTE', 'Urgente')], default='NAO_URGENTE', max_length=20),
        ),
    ]
