# Generated by Django 6.0.3 on 2026-04-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('ativo', models.CharField(choices=[('ATIVO', 'ativo'), ('INATIVO', 'inativo')], default='ativo', max_length=10)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
